#############################################################################
# Makefile for building: Fireworks.app/Contents/MacOS/Fireworks
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Fireworks.pro
# Template: app
# Command: /Users/maryallisonabad/Qt/5.5/clang_64/bin/qmake -o Makefile Fireworks.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/maryallisonabad/Qt/5.5/clang_64/lib
QMAKE         = /Users/maryallisonabad/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Fireworks1.0.0
DISTDIR = /Users/maryallisonabad/Documents/CMSC427/Fireworks/.tmp/Fireworks1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/maryallisonabad/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/maryallisonabad/Qt/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		firework.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		firework.o \
		moc_mainwindow.o
DIST          = ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		Fireworks.pro mainwindow.h \
		firework.h main.cpp \
		mainwindow.cpp \
		firework.cpp
QMAKE_TARGET  = Fireworks
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Fireworks.app/Contents/MacOS/Fireworks

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d Fireworks.app/Contents/MacOS/ || mkdir -p Fireworks.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Fireworks.pro ../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		Fireworks.pro \
		/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Fireworks.pro
../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
Fireworks.pro:
/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Fireworks.pro

qmake_all: FORCE

Fireworks.app/Contents/PkgInfo: 
	@test -d Fireworks.app/Contents || mkdir -p Fireworks.app/Contents
	@$(DEL_FILE) Fireworks.app/Contents/PkgInfo
	@echo "APPL????" > Fireworks.app/Contents/PkgInfo
Fireworks.app/Contents/Resources/empty.lproj: 
	@test -d Fireworks.app/Contents/Resources || mkdir -p Fireworks.app/Contents/Resources
	@touch Fireworks.app/Contents/Resources/empty.lproj
	
Fireworks.app/Contents/Info.plist: 
	@test -d Fireworks.app/Contents || mkdir -p Fireworks.app/Contents
	@$(DEL_FILE) Fireworks.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Fireworks,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Fireworks,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >Fireworks.app/Contents/Info.plist

all: Makefile \
		Fireworks.app/Contents/PkgInfo \
		Fireworks.app/Contents/Resources/empty.lproj \
		Fireworks.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h firework.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp firework.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Fireworks.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		mainwindow.h
	/Users/maryallisonabad/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/maryallisonabad/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/maryallisonabad/Documents/CMSC427/Fireworks -I/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/maryallisonabad/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/maryallisonabad/Qt/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/maryallisonabad/Qt/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		mainwindow.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		firework.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

firework.o: firework.cpp firework.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o firework.o firework.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

